{% set version = "1.50.1" %}

package:
  name: geographiclib
  version: {{ version }}

source:
  - url: https://nchc.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-{{ version }}.tar.gz
    fn: geographiclib-{{ version }}.tar.gz
build:
  number: 11

requirements:
  build:
    - cmake
    - ninja    
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://sourceforge.net/projects/geographiclib/
  license: MIT License
  license_file: LICENSE.txt
  summary: GeographicLib is a small set of C++ classes for converting between geographic

  description: |
    GeographicLib is a small set of C++ classes for converting between geographic, UTM, UPS, MGRS, and geocentric coordinates, for gravity (e.g., EGM2008), geoid, and geomagnetic field (e.g., WMM2010) calculations, and for solving geodesic problems. For documentation, visit https://geographiclib.sf.io.

extra:
  recipe-maintainers:
    - mingwieliu
